services:
  sveltekit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
